config/routes.rb
Rails.application.routes.draw do
  resources :dinosaurs
  resources :cages do
    resources :dinosaurs
  end

end

app/models/cage.rb
class Cage < ActiveRecord::Base
  has_many :dinosaurs

  validates :capacity, presence: true
  validates :current, presence: true
	validates :has_power, inclusion: { in: [true, false] }

  validate :current_less_than_capacity

  after_initialize :update_current

  def current_less_than_capacity
    if self.current > self.capacity
      errors.add(:current, "can't be greater than capacity: #{self.capacity}")
    end
  end

  def update_current
    # update current with dinosaur count
    self.update(current: self.dinosaurs.count);
  end
end

app/models/dinosaur.rb
class Dinosaur < ActiveRecord::Base
  belongs_to :cage

  validates :cage_id, presence: true
  validates :name, presence: true
  validates :species, presence: true

  enum species: [ :Tyrannosaurus, :Velociraptor, :Spinosaurus, :Megalosaurus, :Brachiosaurus, :Stegosaurus, :Ankylosaurus, :Triceratops ]
  enum diet: [ :Herbivore, :Carnivore ]

  after_initialize :set_defaults

  def set_defaults
    # Set diet based on species
    if self.species.in? [ "Tyrannosaurus", "Velociraptor", "Spinosaurus", "Megalosaurus" ]
        self.diet = :Carnivore
    else
      self.diet = :Herbivore
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/cages_controller.rb
class CagesController < ApplicationController
  before_action :set_cage, only: [:show, :edit, :update, :destroy]

  # GET /cages
  # GET /cages.json
  def index
    @cages = Cage.all
  end

  # GET /cages/1
  # GET /cages/1.json
  def show
  end

  # GET /cages/new
  def new
    @cage = Cage.new
  end

  # GET /cages/1/edit
  def edit
  end

  # POST /cages
  # POST /cages.json
  def create
    @cage = Cage.new(cage_params)

    respond_to do |format|
      if @cage.save
        format.html { redirect_to @cage, notice: 'Cage was successfully created.' }
        format.json { render :show, status: :created, location: @cage }
      else
        format.html { render :new }
        format.json { render json: @cage.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cages/1
  # PATCH/PUT /cages/1.json
  def update
    respond_to do |format|
      if !cage_params[:has_power] && @cage.dinosaurs.any?
        # Cannot power down with dinosaurs still inside
        @cage.errors.add(:current, "Cannot power down with dinosaurs inside!")
        format.json { render json: @cage.errors, status: :unprocessable_entity }

      elsif @cage.update(cage_params)
        format.html { redirect_to @cage, notice: 'Cage was successfully updated.' }
        format.json { render :show, status: :ok, location: @cage }
      else
        format.html { render :edit }
        format.json { render json: @cage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cages/1
  # DELETE /cages/1.json
  def destroy
    @cage.destroy
    respond_to do |format|
      format.html { redirect_to cages_url, notice: 'Cage was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cage
      @cage = Cage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cage_params
      params.require(:cage).permit(:capacity, :current, :has_power)
    end
end

app/controllers/dinosaurs_controller.rb
class DinosaursController < ApplicationController
  before_action :set_dinosaur, only: [:show, :edit, :update, :destroy]

  # GET /dinosaurs
  # GET /dinosaurs.json
  def index
    @dinosaurs = params[:cage_id].nil? ? Dinosaur.all : Dinosaur.where(cage_id: params[:cage_id])
  end

  # GET /dinosaurs/1
  # GET /dinosaurs/1.json
  def show
  end

  # GET /dinosaurs/new
  def new
    @dinosaur = Dinosaur.new
  end

  # GET /dinosaurs/1/edit
  def edit
  end

  # POST /dinosaurs
  # POST /dinosaurs.json
  def create
    @dinosaur = Dinosaur.new(dinosaur_params)

    respond_to do |format|
      if Cage.find_by(id: @dinosaur.cage_id).nil?
        # cage does not exist
        @dinosaur.errors.add(:cage_id, "Cage does not exist!")
        format.json { render json: @dinosaur.errors, status: :unprocessable_entity }

      elsif !Cage.find(@dinosaur.cage_id).has_power?
        # don't add dinosaur if cage doesn't have power
        @dinosaur.errors.add(:cage_id, "Cannot add dinosaur to a cage without power!")
        format.json { render json: @dinosaur.errors, status: :unprocessable_entity }

      elsif @dinosaur.Carnivore? && @dinosaur.cage.dinosaurs.Herbivore.any? ||
            @dinosaur.Herbivore? && @dinosaur.cage.dinosaurs.Carnivore.any?
        # don't mix carnivores and herbivores
        @dinosaur.errors.add(:cage_id, "Don't mix carnivores and herbivores!")
        format.json { render json: @dinosaur.errors, status: :unprocessable_entity }

      elsif @dinosaur.Carnivore? && @dinosaur.cage.dinosaurs.where.not(species: Dinosaur.species[@dinosaur.species]).any?
        # don't mix carnivores with different species
        @dinosaur.errors.add(:cage_id, "Cannot add carnivore to cage with species different than itself!")
        format.json { render json: @dinosaur.errors, status: :unprocessable_entity }

      elsif @dinosaur.cage.current >= @dinosaur.cage.capacity
        # don't add to full cage
        @dinosaur.errors.add(:cage_id, "Cannot add to full cage!")
        format.json { render json: @dinosaur.errors, status: :unprocessable_entity }

      elsif @dinosaur.save
        format.html { redirect_to @dinosaur, notice: 'Dinosaur was successfully created.' }
        format.json { render :show, status: :created, location: @dinosaur }
      else
        format.html { render :new }
        format.json { render json: @dinosaur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dinosaurs/1
  # PATCH/PUT /dinosaurs/1.json
  def update
    dest_cage = Cage.find_by(id: dinosaur_params[:cage_id])

    respond_to do |format|
      if dest_cage.nil?
        # cage does not exist
        @dinosaur.errors.add(:cage_id, "Cage does not exist!")
        format.json { render json: @dinosaur.errors, status: :unprocessable_entity }

      elsif !dest_cage.has_power?
        # don't add dinosaur if cage doesn't have power
        @dinosaur.errors.add(:cage_id, "Cannot add dinosaur to a cage without power!")
        format.json { render json: @dinosaur.errors, status: :unprocessable_entity }

      elsif @dinosaur.Carnivore? && dest_cage.dinosaurs.Herbivore.any? ||
        @dinosaur.Herbivore? && dest_cage.dinosaurs.Carnivore.any?
        # don't mix carnivores and herbivores
        @dinosaur.errors.add(:cage_id, "Don't mix carnivores and herbivores!")
        format.json { render json: @dinosaur.errors, status: :unprocessable_entity }

      elsif @dinosaur.Carnivore? && dest_cage.dinosaurs.where.not(species: Dinosaur.species[@dinosaur.species]).any?
        # don't mix carnivores with different species
        @dinosaur.errors.add(:cage_id, "Cannot add carnivore to cage with species different than itself!")
        format.json { render json: @dinosaur.errors, status: :unprocessable_entity }

      elsif dest_cage.current + 1 >= dest_cage.capacity
        # don't add to full cage
        @dinosaur.errors.add(:cage_id, "Cannot add to full cage!")
        format.json { render json: @dinosaur.errors, status: :unprocessable_entity }

      elsif @dinosaur.update(dinosaur_params)
        format.html { redirect_to @dinosaur, notice: 'Dinosaur was successfully updated.' }
        format.json { render :show, status: :ok, location: @dinosaur }
      else
        format.html { render :edit }
        format.json { render json: @dinosaur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dinosaurs/1
  # DELETE /dinosaurs/1.json
  def destroy
    @dinosaur.destroy
    respond_to do |format|
      format.html { redirect_to dinosaurs_url, notice: 'Dinosaur was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_dinosaur
    @dinosaur = Dinosaur.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def dinosaur_params
    params.require(:dinosaur).permit(:cage_id, :name, :species, :diet)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cages_helper.rb
module CagesHelper
end

app/helpers/dinosaurs_helper.rb
module DinosaursHelper
end

app/views/cages/_form.html.erb
<%= form_for(@cage) do |f| %>
  <% if @cage.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cage.errors.count, "error") %> prohibited this cage from being saved:</h2>

      <ul>
      <% @cage.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :capacity %><br>
    <%= f.number_field :capacity %>
  </div>
  <div class="field">
    <%= f.label :current %><br>
    <%= f.number_field :current %>
  </div>
  <div class="field">
    <%= f.label :has_power %><br>
    <%= f.check_box :has_power %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cages/edit.html.erb
<h1>Editing Cage</h1>

<%= render 'form' %>

<%= link_to 'Show', @cage %> |
<%= link_to 'Back', cages_path %>

app/views/cages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cages</h1>

<table>
  <thead>
    <tr>
      <th>Capacity</th>
      <th>Current</th>
      <th>Has power</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cages.each do |cage| %>
      <tr>
        <td><%= cage.capacity %></td>
        <td><%= cage.current %></td>
        <td><%= cage.has_power %></td>
        <td><%= link_to 'Show', cage %></td>
        <td><%= link_to 'Edit', edit_cage_path(cage) %></td>
        <td><%= link_to 'Destroy', cage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cage', new_cage_path %>

app/views/cages/new.html.erb
<h1>New Cage</h1>

<%= render 'form' %>

<%= link_to 'Back', cages_path %>

app/views/cages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Capacity:</strong>
  <%= @cage.capacity %>
</p>

<p>
  <strong>Current:</strong>
  <%= @cage.current %>
</p>

<p>
  <strong>Has power:</strong>
  <%= @cage.has_power %>
</p>

<%= link_to 'Edit', edit_cage_path(@cage) %> |
<%= link_to 'Back', cages_path %>

app/views/dinosaurs/_form.html.erb
<%= form_for(@dinosaur) do |f| %>
  <% if @dinosaur.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dinosaur.errors.count, "error") %> prohibited this dinosaur from being saved:</h2>

      <ul>
      <% @dinosaur.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cage_id %><br>
    <%= f.number_field :cage_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :species %><br>
    <%= f.number_field :species %>
  </div>
  <div class="field">
    <%= f.label :diet %><br>
    <%= f.number_field :diet %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dinosaurs/edit.html.erb
<h1>Editing Dinosaur</h1>

<%= render 'form' %>

<%= link_to 'Show', @dinosaur %> |
<%= link_to 'Back', dinosaurs_path %>

app/views/dinosaurs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Dinosaurs</h1>

<table>
  <thead>
    <tr>
      <th>Cage</th>
      <th>Name</th>
      <th>Species</th>
      <th>Diet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dinosaurs.each do |dinosaur| %>
      <tr>
        <td><%= dinosaur.cage_id %></td>
        <td><%= dinosaur.name %></td>
        <td><%= dinosaur.species %></td>
        <td><%= dinosaur.diet %></td>
        <td><%= link_to 'Show', dinosaur %></td>
        <td><%= link_to 'Edit', edit_dinosaur_path(dinosaur) %></td>
        <td><%= link_to 'Destroy', dinosaur, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dinosaur', new_dinosaur_path %>

app/views/dinosaurs/new.html.erb
<h1>New Dinosaur</h1>

<%= render 'form' %>

<%= link_to 'Back', dinosaurs_path %>

app/views/dinosaurs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cage:</strong>
  <%= @dinosaur.cage_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @dinosaur.name %>
</p>

<p>
  <strong>Species:</strong>
  <%= @dinosaur.species %>
</p>

<p>
  <strong>Diet:</strong>
  <%= @dinosaur.diet %>
</p>

<%= link_to 'Edit', edit_dinosaur_path(@dinosaur) %> |
<%= link_to 'Back', dinosaurs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DinosaurApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>